### PR TITLE
Fixes for failing SRA and ICD10 crossreferences.

### PR DESCRIPTION
**Pull request by christabone**

### CODE REVIEW

**Comment by oblodgett** [comment]
@christabone is this going to require a branch? Or should it be added to a different branch?

**Comment by oblodgett** [comment]
@christabone I think you want to added this to the 1.0.2.3 branch as that has not been released yet and the loader will pick it up.

**Comment by oblodgett** [comment]
@christabone take all that back... this is the RD file and it looks at master for that file.

**Comment by christabone** [comment]
@oblodgett Yea, this is "old school" pulling right from master.

**Comment by christabone** [comment]
@oblodgett Let me know if it looks OK when you have a free minute and we can merge it.

**Pull request merged**
