### PR TITLE
genomeLocation, synonym and systematic name.

### LINKED ISSUE #14: add chromosome and position to basic gene info JSON schema and files
Last week I discussed genome info with the BGI-WG.  We asked today in the technical call, if that can come from genome features working group as implied by BGI-WG.   The GF-WG would rather it come from the basic gene info.

We need to see if we can get this into 0.3

### PR DESCRIPTION
**Pull request by sierra-moxon**
fix #14 added first attempt at genomeLocation and synonym schemas.  Added systematic name to basicGeneInformation as well as genomeLocation collection.

also attempted a .gitignore file.

### CODE REVIEW

**Comment by christabone** [comment]
This looks great -- however I just noticed that there are multiple tabs inserted (overall, the code is formatted for spaces). 

Would that be an easy fix? I can always merge and fix it on my computer (convert all to spaces). This is related to the 'ole issue #1.

**Comment by sierra-moxon** [comment]
yep, d'oh.  I have pushed an "untabify" version up to my fork.  I'll merge this to create another pull request?  or you can. :)

**Comment by khowe** [comment]
For synonyms, should we also have a property for the name-of-the-name, for for display purposes (e.g. "Systematic name" vs "Sequence name").

**Comment by sierra-moxon** [comment]
@khowe - we have this too, we call it "synonymGroup" -- happy to change that attribute name if you have one that is better.  This should likely be an enumeration of some kind as well.

**Pull request merged**
