### PR TITLE
Update SGD section of resourceDescriptors.yaml

### PR DESCRIPTION
**Pull request by edwong57**
Added gene/disease URL under pages for SGD

### CODE REVIEW

**Comment by edwong57** [comment]
I don't have access to create a branch, so I needed to fork it to edit and create pull request.

**Comment by christabone** [comment]
Hi @edwong57, I just sent you an invite to the Alliance GitHub group -- this should allow you to create branches.

**Comment by edwong57** [comment]
Cool, thanks!

________________________________

**Comment by edwong57** [comment]
Will try making change on a branch instead of this.

**Pull request closed without merging**
