### PR TITLE
KANBAN-553: Update resourceDescriptors.yaml

### PR DESCRIPTION
**Pull request by chris-grove**
For HGNC resource descriptors entry:
update http to https
update URL pattern to 
https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:[%s]

### CODE REVIEW

**Comment by sierra-moxon** [comment]
How about we change the URL to: `https://bioregistry.io/hgnc:[%s]`
that way we can make it a bioregistry problem to resolve?

**Comment by christabone** [comment]
@sierra-moxon That's an interesting suggestion. I wasn't even aware they offer a resolution service. Maybe we could look into that in the future? For now it might be easier to get this approved for the upcoming release.

**Comment by sierra-moxon** [comment]
you don't have to use bioregistry, you can use identifiers.org. 
there is no risk here, just prevention of maintaining URLs when they change at the external site.

**Comment by christabone** [comment]
@sierra-moxon I wouldn't mind trying it out. @chris-grove what do you think?

**Comment by christabone** [comment]
@sierra-moxon I'd lean more towards bioregistry only because we know Charles is very active and we've spoken to him on several occasions (in case we require assistance).

**Comment by christabone** [comment]
@sierra-moxon Does this look good to you? Thanks for the recommendation.

**Review by sierra-moxon — APPROVED** [review]
looks good!

**Pull request merged**
