### PR TITLE
Update resourceDescriptors.yaml

### PR DESCRIPTION
**Pull request by edwong57**
added URL for PubMed Central (PMC)

### CODE REVIEW

**Review by gildossantos — APPROVED** [review]

**Review by azurebrd — APPROVED** [review]

**Review by gildossantos — COMMENTED** [review]
There's some debate in the #data-quartermasters Slack channel about whether to use "PMC" or "PMCID" as the db_prefix. Maybe hold this until that's resolved?

**Comment by sierra-moxon** [comment]
> There's some debate in the #data-quartermasters Slack channel about whether to use "PMC" or "PMCID" as the db_prefix. Maybe hold this until that's resolved?

@gildossantos @azurebrd  - I made the PMC vs. PMCID an "or" -- see what you think.

**Comment by azurebrd** [comment]
Thanks @sierra-moxon , I didn't know that was an option :)  Since we're not creating PMC/PMCID objects, just linking out crossReferences, that makes sense.  I guess if we were doing this for a datatype that required making an object in Alliance we'd have to pick one or the other in that case ?

**Comment by sierra-moxon** [comment]
Yep, definitely doesn't fix the problem of deciding which to use - but maybe takes the pressure off the decision?  Either one will now resolve.  @gildossantos seemed to favor PMCID, should we go with that?

**Comment by azurebrd** [comment]
Thanks @sierra-moxon !  Sounds good, I think @edwong57 also prefers PMCID.

**Pull request merged**
