### PR TITLE
Creating distinct MOD URL constructors for molecular and genetic inte…

### PR DESCRIPTION
**Pull request by chris-grove**
…ractions

### CODE REVIEW

**Comment by chris-grove** [comment]
@sierra-moxon 
Here's the JIRA ticket to update the downstream code:

https://agr-jira.atlassian.net/browse/AGR-2543

**Review by azurebrd — APPROVED** [review]

**Comment by azurebrd** [comment]
This probably needs coordination with the downstream processes.  Otherwise perhaps adding back gene/MODinteractions is necessary for this PR to go through.  That is, having them duplicated in the old format and the new format temporarily, and once everything downstream has been updated, remove gene/MODinteractions.

**Comment by chris-grove** [comment]
@azurebrd  OK, thanks. I've added back the old format "gene/MODinteractions" pages

**Comment by azurebrd** [comment]
I'm not familiar with the agr_schemas repo, but it looks like the failure is unrelated to downstream processes affected by the gene/MOD changes.  

python bin/agr_validate.py -s ingest/molecules/moleculeMetadData.json.json -d ingest/molecules/WbSampleMolecule.json
Traceback (most recent call last):
  File "bin/agr_validate.py", line 21, in <module>
    with open(schema_file_name) as schema_file:
FileNotFoundError: [Errno 2] No such file or directory: 'ingest/molecules/moleculeMetadData.json.json'
The command "python bin/agr_validate.py -s ingest/molecules/moleculeMetadData.json.json -d ingest/molecules/WbSampleMolecule.json" exited with 1.

There's an extra '.json' in the command that's running.  This is build #967, and it hasn't passed since build #938 two months ago.  https://travis-ci.org/github/alliance-genome/agr_schemas/pull_requests   I'm not sure whether that means it's okay to merge it (somehow), or whether someone needs to fix the molecule issue.

**Review by azurebrd — APPROVED** [review]

**Pull request merged**
