### PR TITLE
Fixing YAML to validate with Python YAML module

### PR DESCRIPTION
**Pull request by adamjohnwright**
I think we can pull this in on its own. It looks like for the loader and generating the GraphQL schema we will be needing the data_dictionary. These requested changes will be a result of the requirements I am developing for generating the GraphQL schema.  

Here is the command line command I used to test the validity of the YAML files: 

`python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))' < <your-filename>.yaml`

### CODE REVIEW

**Comment by sierra-moxon** [comment]
We do have the starts of a yaml validator - https://github.com/alliance-genome/agr_schemas/blob/master/validate_yaml.py. Maybe you could incorporate the data dictionary validation into it.

**Comment by adamjohnwright** [comment]
@sierra-moxon good idea - taking a look

**Comment by adamjohnwright** [comment]
@sierra-moxon I made it so that the yaml_validator will check that one file that is specified when running the command or if no files are specified it will check all the YAML files.

I am confused by what is going on in the Dockerfile and how tests are run for the PR. It looks like it is calling out to logic that is in the Java repo to run tests for this repo. This does not seem like a good idea. I want to add this validation to the tests that run for the PR to pass, unfortunately I would have to go into another repo/language to add this validation.

**Comment by oblodgett** [comment]
The schema json files are getting validated via the same validation that happens in the FMS. The dockerfile is the validation of those files. The java validator is much more strict then the python validator. Even though the same version of the JSON spec is being used.

**Comment by christabone** [comment]
> I am confused by what is going on in the Dockerfile and how tests are run for the PR. It looks like it is calling out to logic that is in the Java repo to run tests for this repo. This does not seem like a good idea.

To second @oblodgett -- these decisions were made for a specific reason. What might not seem like a good idea might actually be a purposeful implementation (just something to keep in mind). We had serious difficulty with the Python validator when this was first implemented, hence the use of Java for validation.

**Comment by adamjohnwright** [comment]
@oblodgett I remember these conversations now. I don't remember the exact details but I remember us finding the strictness of the JAVA implementation useful. As it seems like we are going to start trying to use the data_dictionary files do you think it would be possible for us to create a script that will for sure be run to test this repo outside of the validation scripts (e.g. tests.py?). From this tests.py we could start by doing the YAML validation and possibly add other tests in the future. This way when new tests are added we won't have to change anything in the JAVA code.  

 @christabone I am just trying to go through the repo and make sense of it. By questioning the current setup and mentioning what I ideally would like I am not trying to say that the design decisions are or were wrong. For this I think we should just document it in the README file I will add it to the README file in this pull request. 

Also sorry about working on the weekend. Our daycare is closing for three weeks. I am going to be trying to get work done whenever I can. 

@oblodgett it the Travis CI file being used at all. If not would you be happy with me deleting it?

**Comment by oblodgett** [comment]
I don't know why we have travis associated. The way the java works is that the Dockerfile points to a directory full of JSON files. Java opens each file and checks for the `"$schema": "http://json-schema.org/draft-04/schema#",` property if its found then it validates it, otherwise ignores it. I would guess there is a yaml validator in java that could do the same thing for the directory full of yaml files.

**Comment by adamjohnwright** [comment]
@oblodgett As you and I didn't know why Travis was still associated and it looked like it wasn't being used anymore, I am removing the Travis file. I have made a simple Makefile to run the tests with a single command "make run". The python command I have made for running the YAML validation is just looking for all YAML files in the project and then validating them. For now, Sierra and I could run it by hand after adjusting a YAML file. I would be happy with this being done either from the JAVA side or from the python script for the CI system. I am guessing at some point the tests will become more sophisticated but for now this will work.

**Comment by sierra-moxon** [comment]
@adamjohnwright - I'd like the test script to continue to run (I don't see its output in gocd).  The test validates that my test data correctly reflects the schema it is intended to emulate.  I'd like this to run on each PR.

**Comment by christabone** [comment]
@adamjohnwright @oblodgett 

The schema repo contains a small subset of data to ensure both the schema <-> sample data are in agreement. The Java validator validates the schema and the FMS validates the full files. But! Travis runs the small sample size against changes in this repo to ensure that changes to the schema don't break the data that is submitted by the DQM. 

In the past, changes to the schema (which are valid and pass the Java validator) can be broken and prevent files from being validated in the FMS. If we test changes in this schema repo to small samples of data, we can prevent this from happening.

Please correct me if I'm wrong @sierra-moxon, it's been a while since we implemented this.

**Comment by devopsagr** [comment]
@christabone I had a quick call with @sierra-moxon after the tech call and what you are saying sounds right. I think it makes sense to have GOCD run the JAVA validation and have Travis CI run the checks in the Travis CI file. This way the developer in the repo can add their own test.

I have just added the WebHook back for Travis CI. It should now be checking all pull requests. I also made it so that the Travis indicator in the README file is pointing to the master branch validation instead of develop. I used the devopsagr GitHub user to set this up.  If anyone notices anything issues with this please let me know. 

I have also upgraded the version of python in the Travis file to 3.5 from 2.x. 

I am not sure if I am not understanding something but the Travis interface shows Travis running about a year ago (before my pull request). @sierra-moxon says it was working. I must be missing something. Either way, I don't think it matters as it is working now. 

@sierra-moxon There were two tests that went into the ingest/genotype folder in the Travis.yml file. These tests were failing. I looked for this folder and did not find it. I took them out. Feel free to check to make sure all the tests you want present are there.  :)

**Comment by christabone** [comment]
Awesome @adamjohnwright , thanks for the update.

**Comment by adamjohnwright** [comment]
@sierra-moxon do you have any remaining concerns with this pull request?

**Pull request merged**
